### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by jsseidel** [dfrommi/groovy-pandoc#1] opened 2016-07-08 16:09 UTC
Forgive me if this is a dumb question, but I can't seem to get a filter working when it returns a list of elements as opposed to a single element or a null list. I'm sure I've just missed something obvious. 

Here's a super simple example:

```
#!/usr/bin/env groovy

import static com.github.dfrommi.pandoc.Pandoc.*
import com.github.dfrommi.pandoc.types.*

toJSONFilter(Header) { Header h ->
    new Para(new Str("header replacement"))
}
```

This works as expected.

But this doesn't:

```
#!/usr/bin/env groovy

import static com.github.dfrommi.pandoc.Pandoc.*
import com.github.dfrommi.pandoc.types.*

toJSONFilter(Header) { Header h ->
    [new Para(new Str("header replacement1")), new Para(new Str("header replacement2"))]
}
```

I'm kind of new to groovy, but I think I'm returning a list of Pandoc elements here that is supposed to replace all headers. When I return a list, I get errors at runtime:

```
Caught: groovy.lang.MissingMethodException: No signature of method: com.github.dfrommi.pandoc.PandocFilter$_walk_closure6_closure7.doCall() is applicable for argument types: (java.util.LinkedHashMap) values: [[content:[Str(text:header replacement1)]]]
```

Returning an empty list, [], works as expected. It in effect removes the conditional element, in this case any Headers.

What am I doing wrong? Any help would be appreciated...

**Comment by jsseidel** [comment] 2016-07-08 17:48
I solved the problem, but I'm not going to submit a patch because I'm not sure if my assumptions of how this should work are correct. The problem is in PandocFilter.groovy, in the `walk` function:

```
res = node.collect {
callActionWithOptionalMeta(it, meta, action)
}.findAll { it != [] }
```

The issue is that when filters return lists, res looks like this:

```
[[Para(content:[Str(text:This was a header)]), Para(content:[Str(text:This was a header2)])], More elements . . .]
```

Note that we have a list within a list. When that happens, this fails:

```
(res as List).each { currentRes ->
    currentRes.children.each{ key, childValues ->
```

because currentRes is a list.

The solution (based on my possibly totally erroneous assumptions) is to add a call to flatten in the first code snippet:

```
res = node.collect {
callActionWithOptionalMeta(it, meta, action)
}.findAll { it != [] }.flatten()
```

**Comment by dfrommi** [comment] 2016-09-25 14:15
@jsseidel Thanks a lot for reporting the bug. 
Please accept my apologies for replying so late, but I somehow missed the issue notification.

Good news: the issue is resolved in **v0.7**. 

Your solution was causing some problems in a few other scenarios, so I've fixed it in a different way. 
The new implementation of `walk` should be way more robust than the previous one and even understandable 😉 

Please give version **0.7** a try and let me know if you find further issues.

**Comment by jsseidel** [comment] 2016-09-25 23:06
This is great. Thanks. Yes, I also discovered that my fix resulted in other issues (particularly where tables are involved, but likely other scenarios as well), which I also found (hacky) solutions for. I have a very large documentation project I'm using groovy-pandoc for, so I will give .7 a try and see if it works as is. Pretty sure if groovy-pandoc 0.7 can survive what I throw at it, it'll survive anything :-)
If it does, would you be open to accepting a few more detailed examples and perhaps some additional documentation?

**Comment by dfrommi** [comment] 2016-09-26 06:49
Thanks a lot for doing the big test run. I'm looking forward hearing of the results.
If you encounter further issues, please let me know.

And of course, I'm very much interested in more examples and documentation! Looking forward to the pull request...

**Comment by jsseidel** [comment] 2016-09-26 12:52
My build ran fine with your changes, so we can call this issue closed, I think. Thanks for reworking that bit of code. I will submit a pull request for a couple of filters I'm using this week or next.

**Comment by dfrommi** [comment] 2016-09-26 14:35
Thanks for the test run

**Closed as completed by dfrommi** 2016-09-26 14:35 UTC
